# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Antony Self hosted'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x.x'  # Update to your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: |
    dotnet test BankNUnitTests/BankNUnitTests.csproj --configuration $(buildConfiguration) --logger trx
  displayName: 'Run Unit Tests'
  continueOnError: false

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.trx'
    testResultsFormat: 'VSTest'
    failTaskOnFailedTests: true
